### PR TITLE
Remove additional `-` in the Copyright line

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Ref: #22

### CODE REVIEW

**Comment by cxw42** [comment]
The two hyphens are actually not wrong --- they represent an en dash.  I understand this is a stylistic point on which reasonable people may differ! :)  I do not think this change is worth a commit of its own.

**Comment by xuhdev** [comment]
As @cxw42 said, when I put in the copyright notice, I used two dashes to represent an [en-dash](https://www.thepunctuationguide.com/en-dash.html). This is not a bug :)

**Comment by cxw42** [comment]
@xuhdev thanks for confirming!  Sorry for taking too much credit --- I should have checked the `blame` before commenting :)

**Comment by PeterDaveHello** [comment]
Cool, good to know that 😅

**Pull request closed without merging**
